version: "3.8"

services:
    server:
        build:
            context: ./server
            dockerfile: server.dockerfile
        expose:
            - "8000"
        restart: unless-stopped

    client:
        build:
            context: ./client
            dockerfile: client.dockerfile
        expose:
            - "3000"
        depends_on:
            - server
        restart: unless-stopped
