version: "3.8"

services:
    server:
        build:
            context: ./server
            dockerfile: server.dockerfile
        expose:
            - "8000"
        restart: unless-stopped
        networks:
            - web

    client:
        build:
            context: ./client
            dockerfile: client.dockerfile
        expose:
            - "3000"
        depends_on:
            - server
        restart: unless-stopped
        networks:
            - web

    caddy:
        image: caddy:2
        container_name: caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - web

networks:
    web:

volumes:
    caddy_data:
    caddy_config:
