services:
    server:
        build:
            context: ./server
            dockerfile: server.dockerfile
        expose:
            - "8000"
        env_file:
            - .env
        restart: unless-stopped
        environment:
            - ENV=production
        volumes:
            - server_cookies:/cookies

    client:
        build:
            context: ./client
            dockerfile: client.dockerfile
        expose:
            - "3000"
        env_file:
            - .env
        depends_on:
            - server
