services:
    server:
        build:
            context: ./server
            dockerfile: server.dockerfile
        ports:
            - "${SERVER_PORT}:8000"
        env_file:
            - .env
        restart: unless-stopped

    client:
        build:
            context: ./client
            dockerfile: client.dockerfile
            args:
                NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - server
        restart: unless-stopped
